config/routes.rb
Rails.application.routes.draw do
  resources :details, :students, :departments, :teachers
  
  get 'profile/home'
  root to: 'profile#home'
  devise_for :users

  
  namespace :api do
    namespace :v1 do
      resources :departments do
        member do
          get 'students_count'
        end
        resources :students
      end    
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    before_create :set_roll_no
    belongs_to :department
    has_many :subjects, through: :department
    
    has_one :user, as: :aspect

    has_one_attached :avatar

    self.per_page = 5
    
    def set_roll_no
        last_roll_no = Student.maximum("roll_no")
        self.roll_no = last_roll_no.to_i + 1
    end

    accepts_nested_attributes_for :department, :subjects
end

app/controllers/api/v1/students_controller.rb
class Api::V1::StudentsController < ApplicationController
    before_action :set_student, :set_department, only: [:show, :update, :destroy]
    before_action :authenticate_user!, except: [:show, :index]

    def index
        @departments = Department.find(params[:department_id])
        @students = Student.where(department_id: @departments.id)
        render json: @students
    end

    def show
        if stale?(last_modified: @student.updated_at)
            render json: @student
        end 
    end
    
    
    def create
        @student = Student.new(student_params)
        if @student.save
            render json: @student, status: :created, location: @student
        else 
            render json: @student.errors, status: :unprocessable_entity
        end    
    end

    def update
        if @student.update(student_params)
            render json: @student
        else
      r     ender json: @student.errors, status: :unprocessable_entity
        end
    end


    def destroy
        @student.destroy
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_student
            @student = Student.find(params[:id])
        end

        def set_department
            @department = Department.find(params[:department_id])
        end
        # Only allow a list of trusted parameters through.
        def student_params
            params.require(:student).permit(:roll_no, :name, :department_id)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :set_student, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, except: [:show, :index]

    def index
        @students = Student.all.order(updated_at: :desc).paginate(page: params[:page])
        @departments = Department.all
    end

    def show
        @department = Department.find(@student.department_id)
        @subject = Subject.where("department_id = #{@department.id}")
    end
    
    def new
        @student = Student.new
    end

    def edit
    end

    
    def create
        @student = Student.new(student_params)

        respond_to do |format|
        if @student.save
            format.html { redirect_to @student, notice: "Student was successfully enrolled." }
            format.json { render :show, status: :created, location: @student }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @student.errors, status: :unprocessable_entity }
        end
        end
    end

    def update
        respond_to do |format|
        if @student.update(student_params)
            format.html { redirect_to @student, notice: "Student was successfully updated." }
            format.json { render :show, status: :ok, location: @student }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @student.errors, status: :unprocessable_entity }
        end
        end
    end


    def destroy
        respond_to do |format|
            if @student.destroy
                format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
                format.json { head :no_content }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @student.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_student
        @student = Student.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def student_params
        params.require(:student).permit(:roll_no, :name, :department_id, :avatar)
        end
end

app/helpers/students_helper.rb
module StudentsHelper
    def date_time_format(time)
        time.present? ? time.strftime("%d %B %Y at %l:%p") : nil
    end
end

app/views/students/_form.html.erb
<div class ="jumbotron" style="width: 50%; margin: auto;">
<%= simple_form_for @student, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :name %>

  <% collections = []
  @department = Department.all %>
  <% @department.each do |d| %>
    <% collections << ["#{d.id}", d.d_name] %>
  <% end %>
  <%= f.input :department_id, as: :radio_buttons, collection: collections, label_method: :second, value_method: :first, class: 'col-lg-4 form-control' %>
  <%= f.file_field :avatar, class: 'col-lg-4 form-control'  %>
  
  <%= f.button :submit, :class => 'btn-primary', data: { disable_by: "Saving" } %>

  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
                
<% end %>
</div>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:roll_no) %></th>
      <th><%= model_class.human_attribute_name(:department_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <!--<td><%= link_to student.id, student_path(student) %></td> -->
        <td><%= student.name %></td>
        <td><%= student.roll_no %></td>
        <td><%= student.department_id %></td>
        <td><%= student.created_at.try(:strftime, ("%d %B, %Y at %l %p")) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                        student_path(student), :class => 'btn btn-default btn-xs' %>
        <% if current_user.admin %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        <% end %>


        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class = "navigation_pagination">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              profile_home_path, :class => 'btn btn-default'  %>


<%= will_paginate @students %>
</div>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:roll_no) %>:</strong></dt>
  <dd><%= @student.roll_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:department_id) %>:</strong></dt>
  <dd><%= @student.department.d_name %></dd>
  <dt><strong>Subjects:</strong></dt>
  <dd><% @subject.each do |s| %>
        <%= s.sub %>
      <% end %>
  </dd>
  <dd><%= image_tag @student.avatar.variant(resize_to_limit: [100, 100]) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>