config/routes.rb
Rails.application.routes.draw do
  resources :details, :students, :departments, :teachers
  
  get 'profile/home'
  root to: 'profile#home'
  devise_for :users

  
  namespace :api do
    namespace :v1 do
      resources :departments do
        member do
          get 'students_count'
        end
        resources :students
      end    
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    before_create :set_id_number
    has_many :subjects
    has_one :user_aspect, as: :aspect
    has_one :user, through: :user_aspect

    self.per_page = 5

    def set_id_number
        last_id_number = Teacher.maximum("id_number")
        self.id_number = last_id_number.to_i + 1
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :set_teacher, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, except: [:show, :index]

    def index
        @teachers = Teacher.all.order(updated_at: :desc).paginate(page: params[:page])
    end

    def show
        @subject = Subject.find(@teacher.subject_id)
    end
    
    def new
        @teacher = Teacher.new
    end

    def edit
    end

    
    def create
        @teacher = Teacher.new(teacher_params)

        respond_to do |format|
        if @teacher.save
            format.html { redirect_to @teacher, notice: "teacher was successfully enrolled." }
            format.json { render :show, status: :created, location: @teacher }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @teacher.errors, status: :unprocessable_entity }
        end
        end
    end

    def update
        respond_to do |format|
        if @teacher.update(teacher_params)
            format.html { redirect_to @teacher, notice: "teacher was successfully updated." }
            format.json { render :show, status: :ok, location: @teacher }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @teacher.errors, status: :unprocessable_entity }
        end
        end
    end


    def destroy
        respond_to do |format|
            if @teacher.destroy
                format.html { redirect_to teachers_url, notice: "teacher was removed destroyed." }
                format.json { head :no_content }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @teacher.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_teacher
        @teacher = Teacher.find(params[:id])
        end

        # Only allow a list of trusted parameters through.
        def teacher_params
        params.require(:teacher).permit(:id_number, :name, :subject_id )
        end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div style="width: 50%; margin: auto; padding: 10px">
<%= simple_form_for @teacher, :html => { :class => 'form-horizontal' } do |f| %>

    
  <%= f.input :name %>
  
  <% collections = []
  @subject = Subject.all %>
  <% @subject.each do |s| %>
    <% collections << ["#{s.id}", s.sub] %>
  <% end %>
  <%= f.input :subject_id, as: :radio_buttons, collection: collections, label_method: :second, value_method: :first %>
  
  <%= f.button :submit, :class => 'btn-primary', data: { disable_with: false } %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                teachers_path, :class => 'btn btn-default' %>
<% end %>
</div>

app/views/teachers/edit.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:id_number) %></th>
      <th><%= model_class.human_attribute_name(:subject_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <!--<td><%= link_to teacher.id, teacher_path(teacher) %></td> -->
        <td><%= teacher.name %></td>
        <td><%= teacher.id_number %></td>
        <td><%= teacher.subject_id %></td>
        <td><%= teacher.created_at.try(:strftime, ("%d %B, %Y at %l %p")) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class = "navigation_pagination">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              profile_home_path, :class => 'btn btn-default'  %>

<%= will_paginate @teachers %>
</div>

app/views/teachers/new.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teacher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:id_number) %>:</strong></dt>
  <dd><%= @teacher.id_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject_id) %>:</strong></dt>
  <dd><%= @subject.sub %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>