config/routes.rb
Rails.application.routes.draw do
  resources :details, :students, :departments, :teachers
  
  get 'profile/home'
  root to: 'profile#home'
  devise_for :users

  
  namespace :api do
    namespace :v1 do
      resources :departments do
        member do
          get 'students_count'
        end
        resources :students
      end    
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /details or /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1 or /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details or /details.json
  def create
    @detail = Detail.new(detail_params)
    @detail.user = current_user

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:department, :roll_no)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_with(model: detail) do |form| %>
  <% if detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_area :department %>
  </div>

  <div class="field">
    <%= form.label :roll_no %>
    <%= form.text_area :roll_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Details</h1>

<% if current_user %>
<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Roll no</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.department %></td>
        <td><%= detail.roll_no %></td>
        <td><%= detail.user_id %></td>
        <td><%= link_to 'Show', detail %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
<h3> Go back and login first</h3>
<% end %>
<br>

<%= link_to 'New Student', "students/new"%>
<%= link_to 'Show Students', "students/show"%>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form', detail: @detail %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p>
  <strong>Department:</strong>
  <%= @detail.department %>
</p>

<p>
  <strong>Roll no:</strong>
  <%= @detail.roll_no %>
</p>

<p>
  <strong>User:</strong>
  <%= @detail.user.email %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>